//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankShibaevaAnna322
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int CardID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public int CardNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CardStatus { get; set; }
        public string CardType { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
