//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankShibaevaAnna322
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposits
    {
        public int DepositID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> DepositAmount { get; set; }
        public Nullable<int> InterestRate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public string DepositStatus { get; set; }
        public string DepositName { get; set; }
        public string DepositType { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string NameOfDeposit { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
