//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankShibaevaAnna322
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        public int LoanID { get; set; }
        public string LoanType { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CreditTerm { get; set; }
        public Nullable<int> InterestRate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> ClientSalary { get; set; }
        public Nullable<int> PaymentAmount { get; set; }
        public string LoanName { get; set; }
        public string LoanSum { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
