//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankShibaevaAnna322
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTypes
    {
        public int TransactionTypeID { get; set; }
        public string TransactionType { get; set; }
    }
}
