//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankShibaevaAnna322
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> RoleID { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
